// <auto-generated />
using DBContextMigrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBContextMigrations.Migrations
{
    [DbContext(typeof(SantaDBContext))]
    partial class SantaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBContextMigrations.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("DBContextMigrations.GiftOfChild", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("giftId")
                        .HasColumnType("int");

                    b.Property<long>("requestID")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("giftId");

                    b.HasIndex("requestID");

                    b.ToTable("GiftsOfChild");
                });

            modelBuilder.Entity("RequestsForSanta.ChildGiftRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Age")
                        .HasColumnType("real");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GiftRequests");
                });

            modelBuilder.Entity("DBContextMigrations.GiftOfChild", b =>
                {
                    b.HasOne("DBContextMigrations.Gift", "gift")
                        .WithMany()
                        .HasForeignKey("giftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestsForSanta.ChildGiftRequest", "request")
                        .WithMany("childGifts")
                        .HasForeignKey("requestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gift");

                    b.Navigation("request");
                });

            modelBuilder.Entity("RequestsForSanta.ChildGiftRequest", b =>
                {
                    b.Navigation("childGifts");
                });
#pragma warning restore 612, 618
        }
    }
}
